apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hw-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi


#Pods use PersistentVolumeClaims to request physical storage
